version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: cmd/scraper/Dockerfile
    depends_on:
      - db
    restart: on-failure
    env_file:
      - config.env
    healthcheck:
      test: [ "CMD", "ps -ef | grep -v grep | grep scraper || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 1

  db:
    image: postgres
    env_file:
      - db.env
    ports:
      - "5432:5432"

  blood-info:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - config.env

