# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build scraper
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of current directory: $(ls)"
        echo "GOROOT: $GOROOT"
        # GOROOT=$(go env GOROOT)
        go build -v ./cmd/scraper

    - name: Build server
      run: go build -v ./cmd/server

    - name: Build cert
      run: go build -v ./cmd/cert

#    - name: Test
#      run: go test -v ./...
