name: Build and test application on push
run-name: ${{ github.actor }} is testing out bloodinfo docker-compose 🚀
on: [push]
jobs:

  build-and-test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: mada
      POSTGRES_PASSWORD: mada
      POSTGRES_DB: bloodinfo
    steps:
      # need checkout before using docker-compose-action
      - uses: actions/checkout@v3
      - name: Staring blood-info and scraper services
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes --remove-orphans --rmi local"
          services: |
            db
            blood-info
            scraper

      - name: Run Tests
        working-directory: ./
        run: pwd && ls -l && docker-compose run --rm test

      - name: Stop
        if: always()
        shell: bash
        run: docker-compose down
