name: Build and test application on push
run-name: ${{ github.actor }} is testing out bloodinfo docker-compose 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using docker-compose-action
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes --remove-orphans --rmi local"
          test-container: "blood-info"
          test-command: "$(wget -q -O- --no-check-certificate https://localhost:8443/station | jq '. | length') -gt 0"
